name: CI - Lint, Format, and Type Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci:
        name: Lint, Format, and Type Check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 'latest'

            - name: Cache Bun dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Lint with ESLint
              run: bunx eslint . --ext .ts,.tsx --max-warnings=0

            - name: Check formatting with Prettier
              run: bunx prettier --check "**/*.{js,ts,tsx,json,md,css,scss}"

            - name: Type check with TypeScript
              run: bunx tsc --noEmit
